import numpy as np

if __name__ == "__main__":
    np.random.seed(2019)
    a = np.random.random()
    print(a)
    a = np.random.random()
    print(a)
    np.random.seed(2017)
    a = np.random.random()
    print(a)
    a = np.random.random()
    print(a)
    np.random.seed(2019)
    a = np.random.random()
    print(a)
    np.random.seed(2017)
    a = np.random.random()
    print(a)
    a = np.random.random()
    print(a)
    np.random.seed(2019)
    a = np.random.random()
    print(a)
    a = np.random.random()
    print(a)